[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
game_multisig_vault = "Dfy3ZqRoiNyfi3YCU3SiQRjFtjMderffymz8vg2NQLAC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/xeony/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
